pages:
  - 'overview.md'
  - 'authentication.md'
  - 'api_reference.md'
  - 'store_profile.md'
  - 'products.md'
  - 'categories.md'
  - 'combinations.md'
  - 'product_classes.md'
  - 'orders.md'
  - 'cart.md'
  - 'customers.md'
  - 'customer_groups.md'
  - 'coupons.md'
  - 'application.md'
  - 'stores.md'
  - 'startersite.md'
  - 'webhooks.md'
  - 'application_storage.md'
  - 'add_to_cp.md'
  - 'shipping_api.md'
  - 'payment_api.md'
  - 'promo_api.md'
  - 'customize_storefront.md'
  - 'jsapi.md'
  - 'sso.md'
  - 'libraries.md'