site_name: Ecwid API Docs

pages:
  - 'includes/_overview.md'
  - 'includes/_authentication.md'
  - 'includes/_api_reference.md'
  - 'includes/_store_profile.md'
  - 'includes/_products.md'
  - 'includes/_categories.md'
  - 'includes/_combinations.md'
  - 'includes/_product_classes.md'
  - 'includes/_orders.md'
  - 'includes/_cart.md'
  - 'includes/_customers.md'
  - 'includes/_customer_groups.md'
  - 'includes/_coupons.md'
  - 'includes/_application.md'
  - 'includes/_stores.md'
  - 'includes/_startersite.md'
  - 'includes/_webhooks.md'
  - 'includes/_application_storage.md'
  - 'includes/_add_to_cp.md'
  - 'includes/_shipping_api.md'
  - 'includes/_payment_api.md'
  - 'includes/_promo_api.md'
  - 'includes/_customize_storefront.md'
  - 'includes/_jsapi.md'
  - 'includes/_sso.md'
  - 'includes/_libraries.md'